### ISSUE TITLE
mysql监控perf 有错误

### ISSUE THREAD

**Issue by zliangbj** [qiueer/zabbix#29]
您好,
按照all in one的guide配置了mysql的zabbix监控
zabbix的mysql.conf启用有mysql_perf.py 和 mysql_all.py
其中mysql_perf.py报错, zabbix_mysql_perf.log日志错误如下:
Traceback (most recent call last):
  File "/usr/local/zabbix_agent_extend/scripts/mysql_perf.py", line 257, in main
    val = mt()
  File "/usr/local/zabbix_agent_extend/scripts/mysql_perf.py", line 202, in get_table_scale
    Created_tmp_disk_tables = self.get_item_tval("Created_tmp_disk_tables")
  File "/usr/local/zabbix_agent_extend/scripts/mysql_perf.py", line 108, in get_item_tval
    val = self.get_value(key)
  File "/usr/local/zabbix_agent_extend/scripts/mysql_perf.py", line 91, in get_value
    (value,code) = self._file_cache.get_val_from_json(key)
  File "/usr/local/zabbix_agent_extend/scripts/qiueer/python/filecache.py", line 38, in get_val_from_json
    resobj = str(alllines[1]).strip()
IndexError: list index out of range

请问这个是什么导致的? 谢谢!

**Comment by zliangbj** [comment]
对了, mysql_all.py执行的没有问题, 目前zabbix的mysql监控很多数值都已经有了
有一部分的数据,如: 
 MySQL-Lock status(waited/immediate)返回Received value [] is not suitable for value type [Numeric (float)]错误.
估计就是mysql_perf.py执行报错有关系.  谢谢!

**Comment by qiueer** [comment]
```
self._file_cache_path = "/tmp/.zabbix_mysql_status_%s.txt" % (port) 
/tmp目录下.zabbix_mysql_status_*文件，看下文件内容和权限
```

**Comment by zliangbj** [comment]
这个文件的权限没有问题, zabbix用户own的 读写权限. 里面也有内容.
-rw-rw-r--   1 zabbix zabbix      11 Dec  1 15:43 .zabbix_mysql_status_3306.txt
cat .zabbix_mysql_status_3306.txt 
1512114186

**Comment by qiueer** [comment]
```
已修复
```
