### ISSUE TITLE
您好，请问这个key是不是没有呢？

### ISSUE THREAD

**Issue by 20100507** [qiueer/zabbix#41]
您好，使用您的mysql监控脚本时，这个key不支持，是我自己的问题么？
custom.mysql.item[running_count]

**Comment by qiueer** [comment]
看下日志呢，或者命令行手动执行下命令，加-d选项




| |
邱景钦
邮箱：qiujqin@163.com
|

签名由 网易邮箱大师 定制

在2018年08月02日 17:59，回眸,境界 写道：

您好，这个key不支持，是我自己的问题么？
custom.mysql.item[running_count]

**Comment by 20100507** [comment]
这是我的web监控平台的历史数据记录
```
 | - other - (2 Items)
  |   | MySQL-活跃链接数custom.mysql.item[running_count] | 60 | 60d | 90d | Zabbix agent |   |   |   | Graph |  
  |   | MySQL-链接数custom.mysql.item[connected_count] | 60 | 60d | 90d | Zabbix agent |   |   |   | Graph |  
```

这是您的mysql.conf文件，文件中并不包含custom.mysql.item这个key？
```
## qiueer mysql-status for mysql @20160125
UserParameter=mysql.status[*],python /etc/zabbix/script/mysql/mysql_status.py -i $1

## qiueer MySQL for Check MySQL Function @20160125
UserParameter=mysql.function[*],python /etc/zabbix/script/mysql/mysql_func.py -i $1

## qiueer MySQL for Perf @20160126
UserParameter=mysql.perf[*],python /etc/zabbix/script/mysql/mysql_perf.py -i $1
```
请问是不是需要自己写python脚本，然后手动添加key到配置文件中呢？

谢谢！！

**Comment by 20100507** [comment]
这些key都是触发器中的key

**Comment by 20100507** [comment]
```
[2018-08-02 21:52:45] ERROR
Traceback (most recent call last):
  File "/etc/zabbix/script/mysql/mysql_status.py", line 144, in main
    value = mysql.get_value(options.key)
  File "/etc/zabbix/script/mysql/mysql_status.py", line 93, in get_value
    (value,code) = self._file_cache.get_val_from_json(key)
  File "/etc/zabbix/script/mysql/qiueer/python/filecache.py", line 38, in get_val_from_json
    resobj = str(alllines[1]).strip()
IndexError: list index out of range
```
