### ISSUE TITLE
python nginx.py -p 80 -k accepts无法获取值

### ISSUE THREAD

**Issue by spritluo** [qiueer/zabbix#43]
我执行python nginx.py -p 80 -k accepts返回结果为空
ERROR:
[2018-08-16 00:54:29] ERROR
Traceback (most recent call last):
  File "nginx.py", line 186, in main
    value = ngx.get_item_tval(key, uri)
  File "nginx.py", line 144, in get_item_tval
    val = self.get_value(key, uri, port=port, iphost=iphost)
  File "nginx.py", line 127, in get_value
    (value, code) = self._file_cache.get_val_from_json(key)
  File "/usr/lib/python2.7/site-packages/qiueer/python/filecache.py", line 38, in get_val_from_json
    resobj = str(alllines[1]).strip()
IndexError: list index out of range

不知道问题出在哪里，能帮忙解答一下吗

**Comment by qiueer** [comment]
nginx配置文件配置好了么。
