### ISSUE TITLE
zabbix 监控mysql的python脚本。 都有问题，都没法执行。 你到底有没有测试这些脚本？？？

### ISSUE THREAD

**Issue by wddphero** [qiueer/zabbix#50]
zabbix 监控mysql的python脚本。 都有问题，都没法执行。 你到底有没有测试这些脚本？？？

**Comment by qiueer** [comment]
@wddphero 具体是什么问题？

**Comment by 37705109** [comment]
[root@zabbix-server zabbix]# zabbix_get -s 192.168.1.31 -p 10050  -k  'custom.redis.item[6379,total_connections_received]'
Traceback (most recent call last):
  File "/usr/local/zabbix/lib/redis/redis.py", line 184, in main
    print redis_ins.get_item(options.key, port=options.port, force=options.force)
  File "/usr/local/zabbix/lib/redis/redis.py", line 99, in get_item
    c2 = cmds(cmdstr, timeout=3)
  File "/usr/local/zabbix/lib/redis/qiueer/python/cmds.py", line 18, in __init__
    self.cmds(*args, **kwargs)
  File "/usr/local/zabbix/lib/redis/qiueer/python/cmds.py", line 23, in cmds
    self.ps = Popen(command, stdout=stdout, stdin=PIPE, stderr=stderr, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1199, in _execute_child
    args = list(args)
TypeError: 'NoneType' object is not iterable

配置了redis监控，所有的键值测试都是报这个错误

**Comment by 37705109** [comment]
[root@zabbix-server zabbix]# zabbix_get -s 192.168.1.31 -p 10050  -k  'custom.redis.item[6379,total_connections_received]'
Traceback (most recent call last):
  File "/usr/local/zabbix/lib/redis/redis.py", line 184, in main
    print redis_ins.get_item(options.key, port=options.port, force=options.force)
  File "/usr/local/zabbix/lib/redis/redis.py", line 99, in get_item
    c2 = cmds(cmdstr, timeout=3)
  File "/usr/local/zabbix/lib/redis/qiueer/python/cmds.py", line 18, in __init__
    self.cmds(*args, **kwargs)
  File "/usr/local/zabbix/lib/redis/qiueer/python/cmds.py", line 23, in cmds
    self.ps = Popen(command, stdout=stdout, stdin=PIPE, stderr=stderr, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1199, in _execute_child
    args = list(args)
TypeError: 'NoneType' object is not iterable

配置了redis监控，所有的键值测试都是报这个错误

**Comment by qiueer** [comment]
可以把执行的命令输出来看一下

在2019年06月20日 16:37，37705109 写道：

[root@zabbix-server zabbix]# zabbix_get -s 192.168.1.31 -p 10050 -k 'custom.redis.item[6379,total_connections_received]'
Traceback (most recent call last):
File "/usr/local/zabbix/lib/redis/redis.py", line 184, in main
print redis_ins.get_item(options.key, port=options.port, force=options.force)
File "/usr/local/zabbix/lib/redis/redis.py", line 99, in get_item
c2 = cmds(cmdstr, timeout=3)
File "/usr/local/zabbix/lib/redis/qiueer/python/cmds.py", line 18, in init
self.cmds(*args, **kwargs)
File "/usr/local/zabbix/lib/redis/qiueer/python/cmds.py", line 23, in cmds
self.ps = Popen(command, stdout=stdout, stdin=PIPE, stderr=stderr, shell=True)
File "/usr/lib64/python2.7/subprocess.py", line 711, in init
errread, errwrite)
File "/usr/lib64/python2.7/subprocess.py", line 1199, in _execute_child
args = list(args)
TypeError: 'NoneType' object is not iterable

配置了redis监控，所有的键值测试都是报这个错误
